# Generated by Django 5.2.14 on 2026-08-20 12:33

import django.db.models.deletion
import pgvector.django.vector
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rolodex", "0064_vanguard_default_client"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the note. Wikilinks resolve against this value.",
                        max_length=255,
                        unique=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "body_markdown",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Markdown body. Use [[Title]] to link to another note.",
                        verbose_name="Body",
                    ),
                ),
                (
                    "exclude_from_rag",
                    models.BooleanField(
                        default=False,
                        help_text="Exclude this note from embedding and AI retrieval if it contains sensitive content.",
                        verbose_name="Exclude from RAG",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kb_notes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional engagement this note belongs to. Leave blank for standalone notes.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kb_notes",
                        to="rolodex.project",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="NoteEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        help_text="Order of this chunk within the note body.",
                        verbose_name="Chunk index",
                    ),
                ),
                (
                    "chunk_text",
                    models.TextField(
                        help_text="The raw text of the chunk that was embedded.",
                        verbose_name="Chunk text",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1536,
                        help_text="Vector representation of the chunk text.",
                        null=True,
                    ),
                ),
                (
                    "excluded_from_rag",
                    models.BooleanField(
                        default=False,
                        help_text="True when this chunk was excluded for sensitive-content reasons.",
                        verbose_name="Excluded from RAG",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="knowledge_base.note",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note embedding",
                "verbose_name_plural": "Note embeddings",
                "ordering": ["note", "chunk_index"],
                "indexes": [
                    models.Index(fields=["note"], name="kb_embedding_note_idx"),
                    models.Index(
                        fields=["excluded_from_rag"], name="kb_embedding_excl_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NoteLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_title_raw",
                    models.CharField(
                        help_text="Raw [[title]] text before resolution, used for broken-link display.",
                        max_length=255,
                        verbose_name="Target title",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="knowledge_base.note",
                    ),
                ),
                (
                    "target_note",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolved target note. Null when the target does not exist yet.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="knowledge_base.note",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note link",
                "verbose_name_plural": "Note links",
                "ordering": ["source_note", "target_title_raw"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_note", "target_title_raw"),
                        name="unique_kb_link_source_title",
                    )
                ],
            },
        ),
    ]
