# Generated by Django 5.2.14 on 2026-08-20 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0002_pgvector_extension"),
        ("rolodex", "0064_vanguard_default_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technique_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MITRE ATT&CK technique ID, e.g. T1059.001.",
                        max_length=20,
                        verbose_name="ATT&CK Technique ID",
                    ),
                ),
                (
                    "tactic",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ATT&CK tactic, e.g. initial-access, persistence.",
                        max_length=50,
                        verbose_name="Tactic",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="When the action occurred.", verbose_name="Timestamp"
                    ),
                ),
                (
                    "action_description",
                    models.TextField(
                        help_text="High-level description of the action taken.",
                        verbose_name="Action",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        default="success",
                        help_text="Did the action succeed, fail, or get blocked?",
                        max_length=20,
                        verbose_name="Outcome",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional operator context (e.g. paused, blackout window).",
                        verbose_name="Note",
                    ),
                ),
                (
                    "sequence_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order of the action within the engagement's attack path.",
                        verbose_name="Sequence order",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target asset of the action, when known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline_entries",
                        to="assets.asset",
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        help_text="Engagement this action belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_entries",
                        to="rolodex.project",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Timeline entry",
                "verbose_name_plural": "Timeline entries",
                "ordering": ["engagement", "timestamp", "sequence_order"],
            },
        ),
        migrations.CreateModel(
            name="RuleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technique_id",
                    models.CharField(
                        help_text="The technique that produced the detection gap.",
                        max_length=20,
                        verbose_name="ATT&CK Technique ID",
                    ),
                ),
                (
                    "draft_rule_xml",
                    models.TextField(
                        help_text="Draft Wazuh/Sigma rule text for the gap.",
                        verbose_name="Draft rule XML",
                    ),
                ),
                (
                    "test_log_sample_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path to a sample log that should trigger the rule.",
                        max_length=500,
                        verbose_name="Test log sample path",
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why this rule is needed and what it should detect.",
                        verbose_name="Justification",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("deployed", "Deployed"),
                            ("rejected", "Rejected"),
                            ("verified", "Verified"),
                        ],
                        default="draft",
                        help_text="Lifecycle state of this request.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sentinel-side identity that approved the request.",
                        max_length=255,
                        verbose_name="Approved by (Sentinel)",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Rejection reason"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rule_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timeline_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional timeline entry that produced the gap.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rule_requests",
                        to="purple_team.timelineentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule request",
                "verbose_name_plural": "Rule requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionVerdict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matched_sentinel_alert_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Alert ID from Sentinel once a match is confirmed.",
                        max_length=255,
                        verbose_name="Matched Sentinel alert ID",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("detected", "Detected"),
                            ("not_detected", "Not Detected"),
                            ("detected_not_escalated", "Detected but not escalated"),
                            ("detected_late", "Detected late"),
                            ("untested", "Untested"),
                        ],
                        default="untested",
                        help_text="Detection outcome for this action.",
                        max_length=30,
                        verbose_name="Verdict",
                    ),
                ),
                (
                    "detection_delay_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Delay between action and detection for 'detected_late' verdicts.",
                        null=True,
                        verbose_name="Detection delay (seconds)",
                    ),
                ),
                (
                    "confirmed_by_operator",
                    models.BooleanField(
                        default=False,
                        help_text="True when the operator accepted the auto-suggested match.",
                        verbose_name="Confirmed by operator",
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_verdicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timeline_entry",
                    models.OneToOneField(
                        help_text="The timeline entry this verdict applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verdict",
                        to="purple_team.timelineentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detection verdict",
                "verbose_name_plural": "Detection verdicts",
                "ordering": ["timeline_entry", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="timelineentry",
            index=models.Index(
                fields=["engagement", "timestamp"], name="timeline_eng_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelineentry",
            index=models.Index(fields=["technique_id"], name="timeline_technique_idx"),
        ),
        migrations.AddIndex(
            model_name="rulerequest",
            index=models.Index(fields=["status"], name="rule_request_status_idx"),
        ),
        migrations.AddIndex(
            model_name="rulerequest",
            index=models.Index(
                fields=["technique_id"], name="rule_request_technique_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectionverdict",
            index=models.Index(fields=["verdict"], name="verdict_value_idx"),
        ),
    ]
