# Generated by Django 5.2.14 on 2026-08-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeTTCTRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_file_path",
                    models.CharField(
                        help_text="Filesystem path of the DeTT&CT output file this run imported.",
                        max_length=500,
                        verbose_name="Output file path",
                    ),
                ),
                (
                    "run_at",
                    models.DateTimeField(
                        help_text="Timestamp of the DeTT&CT job run (from the file's date, or when the job executed).",
                        verbose_name="Run at",
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this snapshot was imported into Vanguard.",
                        verbose_name="Imported at",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Normalized parsed contents of the DeTT&CT output file.",
                        verbose_name="Payload",
                    ),
                ),
            ],
            options={
                "verbose_name": "DeTT&CT run",
                "verbose_name_plural": "DeTT&CT runs",
                "ordering": ["-run_at", "-imported_at"],
            },
        ),
    ]
